### ISSUE TITLE
K8SSAND-78 ⁃ Package k8ssandra for Operator Lifecycle Manager

### ISSUE THREAD

**Issue by sanbornick** [k8ssandra/k8ssandra#120]
**Is your feature request related to a problem? Please describe.**
Manage lifecycle of k8ssandra-tools better.

**Describe the solution you'd like**
Support [Operator Lifecycle Manager](https://olm.operatorframework.io/)
Consider listing on [OperatorHub.io](OperatorHub.io)

**Describe alternatives you've considered**
Helm is the alternative.

**Additional context**
This will aid in managing k8ssandra itself, but will come with all the other goodies of OLM such as UI integration driven by the CRDs.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-78) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-78
┆priority: Medium

**Comment by jsanda** [comment]
Hi @sanbornick 

Thanks for submitting the feature request!

There were multiple factors that went into the decision to go with Helm. Charts can be developed quickly and easily. For people coming to k8ssandra with little or no k8s experience, I think Helm is easier to grasp than things like operators and OLM. With that said, Helm only gets us so far.

While the current focus is on Helm charts, we may look at a custom operator in order to provide full lifecycle management. OLM would definitely compliment that solution nicely. k8ssandra current uses a bunch of operators:

* cass-operator
* prometheus-operator
* grafana-operator
* reaper-operator
* medusa-operator

OLM is certainly a viable solution for managing all of those operator dependencies. I am definitely interested in exploring this and would love to have some discussions. I want to reiterate though that further development of the Helm charts is the immediate priority.

**Comment by bradfordcp** [comment]
cass-operator is packaged in OLM form. We should make a ticket on k8ssandra-operator for this feature.
