### ISSUE TITLE
K8SSAND-1566 ⁃ medusa to backup specific keyspaces

### ISSUE THREAD

**Issue by zencircle** [k8ssandra/k8ssandra#1429]
I do not see option to select a specific keyspace when running medusa backups, can this is be added or am I missing configuration ?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1566) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1566
┆priority: Medium

**Comment by jsanda** [comment]
Medusa does not support this. See [Performing backups](https://github.com/thelastpickle/cassandra-medusa/blob/master/docs/Performing-backups.md). I think that is by design. This is a question/request that has probably come up in the Medusa community. You may want to check the issues in https://github.com/thelastpickle/cassandra-medusa and/or create a new issue there.
