### ISSUE TITLE
K8SSAND-1686 ⁃ Add documentation for CDC

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#1458]
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1686) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1686
┆priority: Medium

**Comment by adejanovski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra/1458?planning-poker) with ZenHub @Miles-Garnsey

**Comment by adejanovski** [comment]
@Miles-Garnsey, I can't find a PR for that issue although it's marked as ready for review. Am I missing something?

**Comment by adejanovski** [comment]
Is it this one? https://github.com/k8ssandra/k8ssandra-operator/pull/639

**Comment by Miles-Garnsey** [comment]
@adejanovski yep, it is. Sorry, I just spotted this.

**Comment by Miles-Garnsey** [comment]
Also, I think I should probably give it another test now that auth: false doesn't trigger an NPE. I wasn't able to do a final validation of the instructions I've given there due to that issue. 

Which makes me wonder if we shouldn't be releasing a new version with that issue fixed before publishing those docs (as they won't work on 1.2.0.)
