### ISSUE TITLE
K8SSAND-1702 ⁃ CRD upgrader is broken for K8ssandra v1.x

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#1478]
Since we made changes to allow the CRD upgrader to support K8ssandra-operator, it seems like we broke it for K8ssandra v1.x.

Here's the traces I've had today when performing an upgrade on a v1.x cluster:

```
2022/07/28 11:45:10 Upgrading CRDs to version 1.5.0
I0728 11:45:11.096540       1 request.go:665] Waited for 1.023299486s due to client-side throttling, not priority and fairness, request: GET:https://10.60.16.1:443/apis/scheduling.k8s.io/v1?timeout=32s
2022/07/28 11:45:12 Downloading release 1.5.0 from Helm repository
2022/07/28 11:45:13 Failed to update CRDs: no chart name found
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1702) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1702
┆priority: Medium

**Comment by adejanovski** [comment]
@Miles-Garnsey, wdyt?

**Comment by Miles-Garnsey** [comment]
Can you please reproduce the steps you followed? This shouldn't be happening, we do have separate upgrade tests for k8ssandra which are passing.

**Comment by Miles-Garnsey** [comment]
If I do the following I see no errors:

```
git checkout v1.3.3 && make create-kind-cluster tools-docker-kind-load && helm install ./charts/k8ssandra k8ssandra
git checkout main && make cert-manager && helm install ./charts/k8ssandra k8ssandra
```

I'm a little confused as to where the new k8ssandra release has come from. We haven't pushed a tag for this by the looks of it? That is probably one cause of the problem.

I think what is happening here is this:

* You are trying to upgrade to 1.5.0 which is an old version.
* All previous versions of k8ssandra used `latest` as the k8ssandra-tools image in the upgrader job.
* That `latest` image now expects a chart name parameter, if it doesn't have one, it fails.

There are two workarounds I can think of off the top of my head:

1. Set a fixed CRD upgrader version in your values.yaml (e.g. [this one](https://hub.docker.com/layers/k8ssandra-tools/k8ssandra/k8ssandra-tools/1.5.1/images/sha256-e6afc055237efadc5cc1372e0e573586b2d15fb001052fa1955839421912a256?context=explore) corresponds to 1.5.1)
2. Publish new charts as 1.5.2 so that the chart versions are compatible with the CRD upgrader (the job spec now includes a chartname parameter).

Going forward we should probably fix the upgrader version to the chart version so that these are in sync. One other thing we could do is re-publish a new CRD upgrader image which takes "k8ssandra" as a default if chartName is not defined. I don't know if I like that as a path forward however.

**Comment by vitaliishandra** [comment]
We are receiving such error during helm upgrade.
Are the any workaround to fix it now or should we wait the fix?
`     - task: HelmDeploy@0
              displayName: "Kassandra Helm upgrade"
              inputs:
                azureSubscription: ${{ parameters.azureServiceConnectionName }}
                azureResourceGroup: $(AKSCluster-ResourceGgroupName)
                kubernetesCluster: $(AKSCluster-Name)
                namespace: saasy
                command: upgrade
                arguments: >
                  --atomic
                  --wait
                  --debug
                  --cleanup-on-fail
                  --timeout 7m59s
                chartType: Name
                chartName: k8ssandra/k8ssandra
                releaseName: jab-cassandra
                overrideValues: |
                  image.pullPolicy=IfNotPresent
                valueFile: "$(Pipeline.Workspace)/glob-outer-loop/ARM-templates/projectartifacts/helm/charts/jab/cassandra.values.yml"
`

**Comment by jeff-knurek** [comment]
sorry, I'm not very clear on the workaround to follow until the next version of the chart is released.
@Miles-Garnsey you said:
> Set a fixed CRD upgrader version in your values.yaml

would that be 
```
client:
  image:
    tag: 1.5.1
```

**Comment by Miles-Garnsey** [comment]
@jeff-knurek, very close, but I think the version you'll want is [here](https://hub.docker.com/layers/k8ssandra-tools/k8ssandra/k8ssandra-tools/1.5.0/images/sha256-f6379221032254e1f0a81c4bdc77094566dc943ca138888f2b678968808758dd?context=explore) (1.5.0), since it looks like we didn't release a CRD upgrader image alongside the 1.5.1 charts. 

I've checked the commit history and nothing changed in the CRD upgrader job between those two tags, so you should be safe using the 1.5.0 image with the 1.5.1 charts.

Apologies for the troubles you're having, I don't feel like we've made this the easiest process. We are having some internal discussions about how to better synchronise the release of the images and charts from this repo.
