### ISSUE TITLE
Helm: The resources limits are not working 

### ISSUE THREAD

**Issue by vitaliishandra** [k8ssandra/k8ssandra#1579]
We pass the resource requests/limits options using the following helm char values:
![image](https://user-images.githubusercontent.com/56965286/217006866-d15e2be2-309f-42ac-9b1e-307b12db5620.png)

But we see another values on DC. How is it calculated? Why our values are not taken into consideration?
![image](https://user-images.githubusercontent.com/56965286/217009097-82d89717-f0f3-4a21-91d9-2786cfd4657c.png)
Chart version: 3.11.10

**Comment by burmanm** [comment]
That information has to come from somewhere else / you have caching issue, we output the input from values.yaml directly to the CassandraDatacenter Spec. There's no additional logic:

https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/templates/cassandra/cassdc.yaml#L90

As k8ssandra 1.x is deprecated, I recommend using k8ssandra-operator in further testing if possible. I'm closing this ticket because of that, if you have further questions, please reopen.

**Comment by vitaliishandra** [comment]
@burmanm  thank you. We updated to k8ssandra-operator some time ago so now we don't have this issue.
