### ISSUE TITLE
Reduce Medusa image size

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#191]
**Is your feature request related to a problem? Please describe.**
The Medusa image currently used in k8ssandra weighs in at over 2 GB.

```
$ docker image ls jsanda/medusa:35d609cd0711
REPOSITORY      TAG            IMAGE ID       CREATED       SIZE
jsanda/medusa   35d609cd0711   f15720643f9b   8 weeks ago   2.02GB
```
That is huge and probably has a lot of unnecessary stuff.

**Describe the solution you'd like**
I would like to prune the image down to only what is actually needed.

**Comment by burmanm** [comment]
```
REPOSITORY                                 TAG        IMAGE ID       CREATED             SIZE
<none>                                     <none>     4a06fc58553c   48 minutes ago      1.06GB
```

After few patches I'm down to that, but there's still a lot of useless stuff in there. The basic problem is that the compilation of dependencies takes a huge amount of additional dependencies which take a lot of disk space. Those build time dependencies are then carried over to the final image, since the Dockerfile has:

FROM base

Instead of ``FROM ubuntu:18.04`` as the final layer, which would then copy files from that build time layer with ``COPY --copy-from base``. However, removing some stuff and replacing the google-cloud-sdk with pip-dependency gsutil I was able to cut down a lot of space.

```diff
diff --git a/k8s/Dockerfile b/k8s/Dockerfile
index 5260d6c..e528ff5 100644
--- a/k8s/Dockerfile
+++ b/k8s/Dockerfile
@@ -1,4 +1,4 @@
-FROM  ubuntu:18.04 as base
+FROM ubuntu:18.04 as base

 RUN mkdir /install
 WORKDIR /install
@@ -8,7 +8,10 @@ RUN apt-get update && \

 RUN add-apt-repository ppa:kalon33/gamesgiroll -y

-RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
+#RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
+
+COPY requirements.txt /requirements.txt
+COPY requirements-grpc.txt /requirements-grpc.txt

 RUN apt-get update \
     && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
@@ -30,19 +33,16 @@ RUN apt-get update \
         apt-transport-https \
         ca-certificates \
         awscli \
-        && mkdir -p /usr/local/gcloud \
-        && tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz \
-        && /usr/local/gcloud/google-cloud-sdk/install.sh --quiet
-
-COPY requirements.txt /requirements.txt
-COPY requirements-grpc.txt /requirements-grpc.txt
-
-RUN pip3 install -r /requirements.txt && \
-    pip3 install -r /requirements-grpc.txt
+        && pip3 install -r /requirements.txt \
+        && pip3 install -r /requirements-grpc.txt \
+        && apt-get remove -y build-essential python3-all-dev python-dev \
+        && apt-get autoclean -y \
+        && apt-get autoremove -y \
+        && rm -fr /root/.cache/pip

 FROM base

-ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin
+# ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin
 ENV DEBUG_VERSION 1
 ENV DEBUG_SLEEP 0

diff --git a/requirements.txt b/requirements.txt
index 0cc77f5..e4be430 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -17,3 +17,4 @@ wheel>=0.32.0
 gevent
 greenlet
 fasteners==0.16
+gsutil
```

That still leaves some unnecessary disk space in the image .. actually quite a lot of it. For example:

/var/cache/lib/apt/lists takes 35MB (from the first apt install layer)
gcc eats 62MB

There's three versions of Python:

drwxr-xr-x         0:0      31 MB  │   │   ├─⊕ python2.7
drwxr-xr-x         0:0      79 MB  │   │   ├─⊕ python3
drwxr-xr-x         0:0      77 MB  │   │   ├─⊕ python3.6

And the dependencies take 300MB also (with grpc-tools taking 84MB).
