### ISSUE TITLE
Enable Stargate by default

### ISSUE THREAD

**Issue by bradfordcp** [k8ssandra/k8ssandra#266]
**Is your feature request related to a problem? Please describe.**
I've heard that Stargate is part of the K8ssandra distribution, but it did not come up as expected with a vanilla `helm install k8ssandra k8ssandra/k8ssandra`

**Describe the solution you'd like**
Stargate should be enabled by default

**Describe alternatives you've considered**
I've considered writing a values.yaml override or passing the flag via CLI, but it seems like the default should be adjusted.

**Additional context**

**Comment by jakerobb** [comment]
How many instances of Stargate by default? Just one?

**Comment by jsanda** [comment]
I thought about this some more I am 👎 . Everyone using k8ssandra is looking to deploy a Cassandra cluster. Not everyone will be looking to also deploy Stargate. To that end it may even be a minority of users. Furthermore, Stargate still _is_ a C* node, albeit coordinator only. This means that it will have non-trivial resource requirements in terms of cpu and memory.

**Comment by jdonenine** [comment]
Does the discussion about resource usage change your opinion here at all @bradfordcp ?

**Comment by jdonenine** [comment]
@bradfordcp if we're enabling stargate by default, what do you think about the following defaults related to it:

* Cassandra Ingress - Switch to disabled by default
* Cassandra Ingress via Stargate - Switched to enabled by default
* Stargate GraphQL Dashboard Ingress - Switched to enabled by default

My thinking here is, if Stargate is on, it should be THE way to interact with the cluster and since our defaults are "developer" focused having the Dashboard on by default makes sense?

**Comment by bradfordcp** [comment]
I agree with everything here except item 2. Given the user MUST have an ingress controller with TCP ingress support installed I would default native protocol ingress to off.

**Comment by jdonenine** [comment]
So you'd turn both the direct Cassandra ingress and the stargate Cassandra ingress to off by default?

I think that's what your saying, but I just want to be clear, since currently the direct ingress is on by default:

https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/values.yaml#L282

**Comment by bradfordcp** [comment]
It is not enabled by default due to `ingress.tearful.enabled` defaulting to false. It only enables after this flag is flipped true.

**Comment by jdonenine** [comment]
You mean `ingress.traefik.enabled`, right? 😄 

I guess my question is rather, if you turn on the traefik ingress, you're going to end up with this by default:

```
ingress:
  traefik:
    enabled: true
    repair:
      enabled: true
    cassandra:
      enabled: true
    stargate:
      enabled: true
      graphql:
        enabled: true
        playground:
          enabled: true
      rest:
        enabled: true
      cassandra:
        enabled: false
```

So you are left in a place where Stargate is enabled for everything besides CQL, CQL goes directly.

Is that the default you'd expect?  I think I'd expect everything to go through Stargate by default - since Stargate is on.

**Comment by jsanda** [comment]
>Given the user MUST have an ingress controller with TCP ingress support installed I would default native protocol ingress to off.

@bradfordcp if all access is going through

**Comment by bradfordcp** [comment]
Autocorrect strikes again. Yes, I would expect that if stargate is enabled we use it for native protocol traffic instead of routing directly to C*. Although I expect the syntax to be a little different given the comments in #253

**Comment by jakerobb** [comment]
For what it's worth:

If the user has Traefik installed on their cluster, I'd want CQL ingress to work by default. Having the Traefik-specific CR applied for CQL ingress is harmless when Traefik is not present. So I'd argue for keeping CQL ingress enabled by default (assuming ingress is enabled at all).

(And yes, it all changes when we do #253)
