### ISSUE TITLE
Docs should include information about how to verify deployment

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#279]
**Is your feature request related to a problem? Please describe.**
After running the installation as described in the docs, how do I know if things are working and deployed as expected?

**Describe the solution you'd like**
It would be great to add some steps and context to the docs related to verifying the state of a deployment based on the different components that have been deployed.  What resources do I need to check? How do I tell what state each resource is in?

**Comment by bradfordcp** [comment]
Items to consider

1. kubectl get pods (check status 2/2, what does 1/2 mean)
2. kubectl describe cassdc (check status section)
3. kubectl exec nodetool status - How does this change with JMX auth being enabled?

**Comment by jsanda** [comment]
I think checking the cassdc status should be the first check. The readiness probe for the `cassandra` container involves a CQL query against the `system.local` keyspace. This is a good check because it tells us that the node is ready to service client requests. Queries against `system.local` do not however hit other replicas. This is why it is good to do the initial check at the CassandraDatacenter level. The CassandraDatacenter is only considered ready when all of the Cassandra pods are ready.

I do not think the readiness probe checks JMX connectivity. Since we are enabling JMX authentication, I think it would be good to also check `nodetool status`.

In addition to Cassandra itself we should also consider the following:

* Reaper
* Stargate
* Prometheus
* Grafana.

I can provide additional details on the above in follow up comments if that would be useful.
