### ISSUE TITLE
K8SSAND-114 ⁃ Store commit log on separate volume

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#351]
**Is your feature request related to a problem? Please describe.**
cass-operator creates a PersistentVolumeClaim for `/var/lib/cassandra`. Both the commit log and the data directory are stored on this volume. With spinning disks it is strongly recommended to store the commit log and the data directory on separate disk. Having them on the same disk is less of an issue with SSDs. I think it is still generally a good practice to separate the commit log and data directory onto separate volumes. Both the storage and performance requirements differ, so having separate volumes make it possible to utilize storage classes and disks better suited for each.

**Describe the solution you'd like**
https://github.com/datastax/cass-operator/issues/327 added support for creating additional PVCs. The default for k8ssandra should be to have a separate PVC for the commit log.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-114) by [Unito](https://www.unito.io)
┆epic: Advanced Component Configuration
┆friendlyId: K8SSAND-114
┆priority: Medium

**Comment by jdonenine** [comment]
@jsanda you referenced this issue in #1183 but when we talked the other day we mentioned that settings related to stuff that requires volume mounts etc not being terribly safe to configure directly... that applies here?

Would this now be possible with the addition of #1183? If so, we should probably document how to do this, if nothing else here in the ticket?  What do you think?

**Comment by jsanda** [comment]
It's not possible with #1183. I listed it under the non-goals. Properties that involve volume mount require some additional work that I thought would be better to tackle in a separate PR. Do you want me to try to do this for 1.4?

**Comment by bradfordcp** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra/351?planning-poker) with ZenHub @adutra @burmanm @jeffbanks @jsanda @Miles-Garnsey

**Comment by bradfordcp** [comment]
I'm a little concerned about the IOPS available to a commit log volume that is smaller in size compared to the volume for data (since IOPS tend to be provisioned compared to total disk capacity). In any case let's get some estimates on this.

**Comment by jsanda** [comment]
Please provide estimates based on doing this in k8ssandra-operator.

**Comment by Miles-Garnsey** [comment]
Sorry I missed this earlier. The changes required are as follows:

1. The cassandra.yaml needs to be updated to reflect the new location.
2. A PVC needs to be created using the `AdditionalVolumes` field [here](https://github.com/k8ssandra/cass-operator/blob/master/apis/cassandra/v1beta1/cassandradatacenter_types.go#L258). 

I estimate 5 days total, mostly because we'd want extensive tests written for this.

However, I also have some reservations about this work. 

1. Does anyone want to do this (especially bearing in mind Chris' comments RE IOPS scaling with disk size)?
2. I feel that this adds a fair bit of complexity to k8ssandra-operator to support a very small number of real-world use cases. I'd rather move towards offering better escape hatches into the lower API layers (e.g. a `CassandraDatacenterTemplate` which offers the `CassDC` API from inside `K8ssandraCluster`) to support advanced users more generally than work on something that we might come to see as tech debt in future.

**Comment by adejanovski** [comment]
This is now possible in k8ssandra-operator and we have both tests [and docs for it](https://github.com/k8ssandra/k8ssandra-operator/blob/main/docs/separate-commitlog-volume.md).
Closing this ticket.

**Comment by doronl** [comment]
Hi @adejanovski @jsanda @Miles-Garnsey  just to understand the final, is this supported? if yes are there any examples/docs (links are broken)? if not, can this be added? this is recommended by DataStax...

Thanks!

**Comment by adejanovski** [comment]
Yes, you'll find the docs in an older tag: https://github.com/k8ssandra/k8ssandra-operator/blob/v1.5.1/docs/separate-commitlog-volume.md

The current docs show more generic information around adding extra volumes: https://github.com/k8ssandra/k8ssandra-operator/blob/main/docs/content/en/tasks/inject/_index.md#injecting-volumes
