### ISSUE TITLE
Document Cassandra auth support

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#353]
**Is your feature request related to a problem? Please describe.**
k8ssandra enables Cassandra authentication and authorization by default. There have been a number of changes made in support of this including:

* #151 
* #153
* #154
* #159 
* #261
* #323 (This is post-1.0 but worth noting in the docs)

**Describe the solution you'd like**
* Provide details on the roles that are created
* Explain how secrets can be created/configured
* Explain why it is good for auth to be enabled by default
* Discuss authorization support (or lack thereof currently)

**Comment by johnsmartco** [comment]
John @jsanda  has kindly offered to write the Auth topic.

**Comment by jsanda** [comment]
@johnsmartco I will work on it this week. Maybe we can schedule some time later in the week to review/discuss.

**Comment by johnsmartco** [comment]
With thanks to @jsanda, this issue is addressed by https://docs.k8ssandra.io/tasks/secure/.  Closing this issue. 

Note: The content is currently on the johnsmart-infoarch branch while we reorg the docs IA, and (by design) already pushed externally to the new subdomain, docs.k8ssandra.io. We'll merge johnsmart-infoarch to main later this week, before KubeCon Europe. The Docs link on k8ssandra.io will link to docs.k8ssandra.io, instead of k8ssandra.io/docs. For all intents and purposes we're good with closing this addressed Security ticket.
