### ISSUE TITLE
Document Cassandra JMX configuration and access 

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#354]
**Is your feature request related to a problem? Please describe.**
When Reaper is enabled, Cassandra is configured with remote JMX enabled. Furthermore JMX authentication is turned on as well. We currently lack docs on this.

**Describe the solution you'd like**
Explain the JMX configure that is used and why it is necessary. We also need to cover using `nodetool`. #322 is relevant here.

**Comment by johnsmartco** [comment]
With thanks to @jsanda, this issue is addressed by https://docs.k8ssandra.io/tasks/secure/.  Closing this issue. 

Note: The content is currently on the johnsmart-infoarch branch while we reorg the docs IA, and (by design) already pushed externally to the new subdomain, docs.k8ssandra.io. We'll merge johnsmart-infoarch to main later this week, before KubeCon Europe. The Docs link on k8ssandra.io will link to docs.k8ssandra.io, instead of k8ssandra.io/docs. For all intents and purposes we're good with closing this addressed Security ticket.
