### ISSUE TITLE
Document how to migrate an existing C* cluster on k8s to k8ssandra

### ISSUE THREAD

**Issue by flightc** [k8ssandra/k8ssandra#377]
**Is your feature request related to a problem? Please describe.**
I was assisting a user having issues with their existing C* 3.11.2 cluster running on k8s. I suggested they'd probably be better off using k8ssandra. It would've been nice if we had a document/guide for migrating their cluster to k8ssandra.

**Describe the solution you'd like**
At the very least, a high level plan for migrating an existing C* cluster on k8s to k8ssandra.

Not necessarily looking for tooling or automation here but just a guide for users.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by jsanda** [comment]
@flightc thanks for creating this. If there are no issues with running another DC on a later 3.11.x, then one way to do this would be a DC migration. 

One question I have is what if anything can we do to automate the process.

**Comment by johnwfrancis** [comment]
Hi all, I've assigned this to myself, but I'll need precise information.

**Comment by jsanda** [comment]
@johnwfrancis this will involve a datacenter migration and possibly some code changes to support it. Things get more complicated if the existing cluster is running outside of the kubernetes cluster. It will involve networking setup outside the scope of k8ssandra and will also require functionality provided in #548. 

I am more than happy to work on this with you 😄

**Comment by jsanda** [comment]
There are a couple different things to come from this ticket. First, provide documentation on how to migrate a C* cluster already running in k8s to k8ssandra. Secondly, create additional tickets as necessary to support the migration.

For the migration, I want to offer a couple different options:

* In-place with existing PVs
* DC switch

### In-place with existing PVs
With this strategy we delete the current Cassandra cluster but keep the PVs. We then create PVCs in advance for our k8ssandra cluster, and those PVCs are bound to the original cluster's PVs.

**Pros**
* Does not require additional resources in terms of cpu, memory, and most importantly storage
* Faster than DC switch
* Simpler than DC switch in terms of the steps involved
* No changes required to application, client services

**Cons**
* Requires downtime
* Less flexible than DC switch
    * Requires same cluster topology
* May be more complicated with non-standard configuration
    * For example, additional steps required if you use a non-default data directory (default is `/var/lib/cassandra`)   

### DC switch
With this strategy we install k8ssandra and configure the two DCs so that cluster. We go through the steps to stream data to the new DC, switch client services over to the new DC, and then decommission the original DC.

**Pros**
* No downtime
* More flexible than in-place migration
    * You can have a different cluster topology
    * You can have a different cluster configuration

**Cons**
* Slower than in-place migration
* Requires additional resources
    * Will require approximately double the storage until the migration is complete
* More steps involved than in-place migration

**Comment by jsanda** [comment]
After more testing today with the [bitnami/cassandra] chart I decided to focus on the DC switch. There are a lot of different things that can vary with the in-place approach that will make writing general instructions difficult. For example, there could be permission issues that might prevent the user in the k8ssandra container from accessing the volume. Another problem which I ran into involved the data directory. The bitnami chart uses a non-default location. When I mounted the volume in my k8ssandra container, the directory structure was incorrect.
