### ISSUE TITLE
Using a private docker registry

### ISSUE THREAD

**Issue by Jeremya** [k8ssandra/k8ssandra#420]
I would like to deploy k8ssandra using exclusively a private docker registry (artifactory in my case). I won't have the ability to pull external docker images. 

Today, I have to rewrite all images url to target my private registry. When I will upgrade to k8ssandra new version, I cannot be sure I won't have to do it again...

Would be interesting to implement the [imagePullSecret](https://github.com/datastax/cass-operator#using-a-custom-docker-registry-with-the-helm-chart) from cass-operator in k8ssandra. Another option would be to have a mirror registry we could specify.

┆Issue is synchronized with this [Jira Feature](https://k8ssandra.atlassian.net/browse/K8SSAND-120) by [Unito](https://www.unito.io)
┆Epic: Image Access Enhancements
┆Fix Versions: k8ssandra-1.3.0

**Comment by bradfordcp** [comment]
Hi @Jeremya, thanks for the enhancement request! Let's take a look at the details and see if we can figure out a solution.

Digging into the `imagePullSecret` feature it looks like you still have to set the full image coordinates for any image in use (in the case of the example they set the coordinate of the cass-operator container to GHCR). You would still have to set the registry / coordinates of the C*, busybox, etc images inside the `CassandraDatacenter` definition. `imagePullSecret` allows you to set the credentials used while pulling those images from a private registry. 

Looking at cass-operator a bit more there _is_ an environment variable `DEFAULT_CONTAINER_REGISTRY_OVERRIDE` that can be set on the deployment to default the registry to something other than `docker.io`. You would most likely want to use this along with the `imagePullSecret` configuration settings.

The [code](https://github.com/datastax/cass-operator/blob/73b010dfce267e289166ee8119431c96f7741774/operator/pkg/images/images.go#L139-L149) it appears as though there is an assumption that your private registry must follow the same image / tag format as what is put out on Docker Hub. For example, if you are looking to deploy `datastax/cassandra:3.11.6-ubi7` and your private registry is `localhost:5000`, it would attempt to pull the image at `localhost:5000/datastax/cassandra:3.11.6-ubi7`.

**Does this behavior align with what you expect?**

**How should we communicate which images are expected to be available from a registry for a given version of K8ssandra?**

I'm looking forward to ironing out the details here and putting something on the roadmap. With the changes to request limits on Docker hub, this is certainly a valuable feature.

**Comment by Jeremya** [comment]
Hi @bradfordcp,

Thanks for your answer, you're perfectly right. I would also need `DEFAULT_CONTAINER_REGISTRY_OVERRIDE`.

Keeping same image and tag format as docker hub should not be a problem.

> How should we communicate which images are expected to be available from a registry for a given version of K8ssandra?
Great question. Would it be a good idea to have a kind of dependencies list in the README or in release notes?

**Comment by grtrout** [comment]
Any update on this issue? And/or can anyone describe the steps needed to install with a private registry?

Assuming all of the image names are described in values.yaml, modifying them is straightforward and easy enough. In my case, I simply prepend my private registry before the image name. That is, **datastax/cassandra-mgmtapi-3_11_10:v0.1.23** becomes **harbor.company.com/project/datastax/cassandra-mgmtapi-3_11_10:v0.1.23**

But this will fail since the service account does not have the proper _imagePullSecrets_ value. I'm OK with manually creating it in the namespace, but it would be great if it could at least be associated with the service account in the helm values.yaml file. This is how I've used helm charts for other projects (GitLab Runner, ArgoCD, Prometheus, Grafana, nginx-ingress, etc.)

**Comment by jsanda** [comment]
Hi @grtrout 

I don't think there has been any work done on this yet. I will spend some time looking into it within the next couple days and report back what I think will be involved.

**Comment by jsanda** [comment]
It looks like you can specify image pull secrets for a ServiceAccount. Maybe we could look at a set of global image pull secrets that would then get added to all ServiceAccounts. I suppose we would want to do something similar for image registries. We would expose this through the k8ssandra-common chart which uses [bitnami/common](https://github.com/bitnami/charts/blob/master/bitnami/common). It looks like [bitnami/common](https://github.com/bitnami/charts/blob/master/bitnami/common) may already provide what we need.

As @bradfordcp mentioned we could use `DEFAULT_CONTAINER_REGISTRY_OVERRIDE` for cass-operator. We will need additional Helm template updates in support of this. For example, we are not specifying a ServiceAccount for Reaper or Stargate. We probably need to go through each component and see what if/anything needs to be done.

**Comment by jsanda** [comment]
The cass-operator Helm chart exposes the `DEFAULT_CONTAINER_REGISTRY_OVERRIDE` env var via the `image.registryOverride` chart property. I have done some initial testing, and it appears to work for the cassandra, busybox, and config-builder images. There is a catch though. It does not work if you explicitly set the image for them which is what we currently do in k8ssandra.

Rather than using `DEFAULT_CONTAINER_REGISTRY_OVERRIDE` I would prefer a registry property in the k8ssandra chart and explicitly set the coordinates for each image. This provides more flexibility than the env var.

For the image pull secrets the CassandraDatacenter spec has a `serviceAccount` property that we can expose in the k8ssandra chart. Then you can point to a service account that is configured with the secrets.

Note that we may need additional changes for other images that k8ssandra deploys.
