### ISSUE TITLE
Document how k8ssandra creates and manages secrets

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#441]
k8ssandra can create and update a number of secrets for different credentials. We need to document several things including:

* How or when the different secrets get created
* How or when secrets get updates
* How or when secrets will get deleted
* Using your own secrets

**Comment by johnsmartco** [comment]
With thanks to @jsanda, this issue is addressed by https://docs.k8ssandra.io/tasks/secure/.  Closing this issue. 

Note: The content is currently on the johnsmart-infoarch branch while we reorg the docs IA, and (by design) already pushed externally to the new subdomain, docs.k8ssandra.io. We'll merge johnsmart-infoarch to main later this week, before KubeCon Europe. The Docs link on k8ssandra.io will link to docs.k8ssandra.io, instead of k8ssandra.io/docs. For all intents and purposes we're good with closing this addressed Security ticket.
