### ISSUE TITLE
K8SSAND-73 ⁃ Cron Medusa purge on a regular basis to remove obsolete backups

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#518]
Medusa has a `purge` command which deletes backup that are candidate for removal based on the configured values for `max_backup_age` and `max_backup_count`.

This command has to run on a regular basis and should be coupled here with cleaning up CassandraBackup resources.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-73) by [Unito](https://www.unito.io)
┆epic: Backup/Restore Enhancement (Purge, Encryption)
┆fixVersions: k8ssandra-operator-v1.1.0
┆friendlyId: K8SSAND-73
┆priority: Medium

**Comment by burmanm** [comment]
Actually, the deletion should happen in the way that CassandraBackup is deleted. That calls the DeleteBackup (after PR) from Medusa. It should never happen that we first call medusa's delete and later CassandraBackup delete as the latter one has finalizer.

**Comment by jsanda** [comment]
>It should never happen that we first call medusa's delete and later CassandraBackup delete as the latter one has finalizer.

I agree, but unless medusa-operator has complete control over the bucket (which in general is unlikely), we have to account for the possibility of an out of band delete where the backup is deleted directly from the bucket. Typically an object's spec is the source of truth. For example if I create a Deployment with two pods and then manually delete a pod, the deployment controller will create a new pod. I think we have to treat the backup situation differently. 

If we find that the backup does not exist in the bucket, then I think we should update the status of the CassandraBackup to reflect this to inform the owner that the actual backup has been deleted.

We should also take into consideration whatever scheduling solution we decide on for #521. 

I am going to change the complexity to high on this. I think it may turn out to be rather involved.

**Comment by burmanm** [comment]
I don't think we have to account for someone deleting all the backups directly from the storage layer. Or if someone removes the rights or modifies them. This could also be temporary issue or permanent, would we automatically return the objects also if they reappear? What if someone pushes something directly to the storage? What if network times out, should we delete them?

I think the CassandraBackup should be the source of truth in installation. Otherwise we're not creating the "Kubernetes native" installation. We should go as far as prevent any direct contact with medusa. All communication with backups should happen through the medusa-operator, through objects in Kubernetes. 

We can't assume backup utility to work if someone deletes the backups, or overwrites them with their video collection. It's just not something we should worry about and it's not something Kubernetes will worry about.

**Comment by jsanda** [comment]
>I don't think we have to account for someone deleting all the backups directly from the storage layer. Or if someone removes the rights or modifies them.

We do have to account for it to some extent. Suppose you have one person who is able to manage Kubernetes and another person who is able to manage S3. The S3 owner deletes some old backups. I don't think we should automatically delete the CassandraBackups, but I think we should reflect in the status that the corresponding backups in S3 are gone.

>would we automatically return the objects also if they reappear? What if someone pushes something directly to the storage? 

Great questions and I lean towards no for both since we aren't sure who/what actually created those objects in the S3 bucket.

>What if network times out, should we delete them?

no

>I think the CassandraBackup should be the source of truth in installation. Otherwise we're not creating the "Kubernetes native" installation. 

We have to consider beyond installation though. We are definitely _not_ creating Kubernetes native resources which is fine. There are plenty of examples of this in practice. It just requires extra thinking and planning which is happening in part now 😉 

>All communication with backups should happen through the medusa-operator, through objects in Kubernetes.

The only way we can guarantee this is if medusa-operator is in complete control over the remote storage. But even then I think this is unlikely. We still need the user to supply an an access key. That person will still have access to the bucket.

>We can't assume backup utility to work if someone deletes the backups, or overwrites them with their video collection. It's just not something we should worry about and it's not something Kubernetes will worry about.

Agreed that we cannot assume things to work if someone deletes a backup outside of Kubernetes. But given it is very real possibility, I absolutely think we need to handle this situations in some way. The backup being deleted is an easy one IMO. We can easily detect that and reflect that in the status of the CassandraBackup object. The user can then decide what to do from there.

These questions and concerns apply to any non-k8s native resources. For example, let's say we build a controller to manage Cassandra roles and permissions. It is a very similar situation. I create a CassandraRole custom resource which results in a role being created in Cassandra. Then someone modifies or deletes that role directly in Cassandra. What should happen with respect to the CassandraRole object. I don't know that there is a right or wrong answer, but I think the question does need to be considered at a minimum.

**Comment by ajvn** [comment]
@jsanda @adejanovski Hi, so how does one setup backup cleaning?

At the moment we're in situation where daily backup grows 2-4 GiB in size, setting like `max_backup_age` doesn't seem to do anything, neither does uninstalling backup charts via Helm.

Storage location is Azure Blob storage, and Meudsa has necessary write/delete permissions.

**Comment by jsanda** [comment]
I believe `max_backup_age` is looked at when running `medusa purge`. That command is neither exposed in k8ssandra nor part of Medusa's gRPC API that is used in k8ssandra. 

For now I suggest running `medusa purge` outside of k8s or create a k8s job that deploys Medusa and calls `medusa purge`. This could be a CronJob.

**Comment by ajvn** [comment]
Thank you for your input, managed to set it up using Debian package, pip installation approach is very slow.

Needed steps (outside of the cluster):
* Install Medusa.
* Adjust Medusa config and credentials file to reflect proper storage backend, and backup age. Potentially set log level to DEBUG.
* Execute this command for each K8ssandra pod you have, `fqdn` value is name of the K8ssandra pod (can be done in parallel):
```bash
medusa --verbosity --fqdn <name-of-the-pod> purge
```
Wait, this will take a while, depending on the cluster size.
* Remove backups in the cluster that were removed from the storage using Helm:
```bash
helm -n <name-of-k8ssandra-namespace> uninstall <name-of-the-backup>
```

Tested this on staging cluster, will also test restoring from backup that was not removed some day next week. 
If that goes fine, I'll test this in production and report here how it went.

**Comment by ajvn** [comment]
This is done in production as well, and it works fine (for around a week now). After initial cleanup which took longer and was done with solution described above (and in parallel), I went ahead with Kubernetes CronJob automated solution which runs daily.

It looks something like this, and it's Azure centric (you can adjust this by specifying different cloud provider dependencies, as described [here](https://github.com/thelastpickle/cassandra-medusa/blob/master/docs/Installation.md#debian-packages):
* Dockerfile:
```bash
FROM ubuntu:18.04

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV DEBUG_VERSION=0

RUN apt-get update && \
    apt-get install -y software-properties-common curl apt-transport-https lsb-release && \
    curl -o setup.deb.sh "https://dl.cloudsmith.io/public/thelastpickle/medusa/setup.deb.sh" && \
    bash setup.deb.sh && \
    # azure-cli repository and gpg
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | \
    gpg --dearmor | \
    tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null \ && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main" | \
    tee /etc/apt/sources.list.d/azure-cli.list && \
    apt-get update && \
    apt-get install -y cassandra-medusa azure-cli

RUN groupadd -r medusa --gid=999 && useradd -r -g medusa --uid=999 --create-home medusa

RUN rm -rf /var/lib/apt/lists/*

USER medusa
WORKDIR /home/medusa

COPY --chown=medusa:medusa --chmod=0755 ["docker-entrypoint.sh", "/home/medusa/docker-entrypoint.sh"]

ENTRYPOINT ["/home/medusa/docker-entrypoint.sh"]
```
* Build it with buildkit option enabled:
```bash
DOCKER_BUILDKIT=1 docker build -t medusa-cassandra-purger:1.0.0 -f Dockerfile .
```
* Script that goes pod by pod, and purge backups as configured in configuration file (available as ConfigMap below):
```bash
#!/usr/bin/env bash
set -Eeuo pipefail

FQDN=("<name-of-k8ssandra-pod-1>"
"<name-of-k8ssandra-pod-2>"
"<name-of-k8ssandra-pod-3>"
"<name-of-k8ssandra-pod-4>"
"<name-of-k8ssandra-pod-5>"
"<name-of-k8ssandra-pod-6>")

for fqdn in "${FQDN[@]}"; do
    medusa --verbosity --config-file /etc/medusa/medusa.ini --fqdn "$fqdn" purge
    echo "============================================================================"
done
```
* ConfigMap for CronJob, and Medusa config file:
```bash
---
apiVersion: v1
data:
  medusa.ini: |-
    [storage]
    storage_provider = azure_blobs
    bucket_name = <name-of-the-bucket>
    key_file = /etc/medusa-secret/medusa_azure_credentials.json
    prefix = <bucket-prefix-in-azure-blob-container>
    max_backup_age = 10
    multi_part_upload_threshold = 104857600
    backup_grace_period_in_days = 10

    [logging]
    level = INFO
kind: ConfigMap
metadata:
  name: k8ssandra-prd-medusa-purge-job-cm
  namespace: <k8ssandra-namespace>

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k8ssandra-prd-medusa-purge-backups-job
  namespace: <k8ssandra-namespace>
spec:
  schedule: "28 13 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
          restartPolicy: OnFailure
          containers:
          - name: k8ssandra-prd-medusa-purge-backups
            image: "<url-of-image-registry>/<path-to-image>/medusa-cassandra-purger:1.0.0"
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 1
                memory: 64Mi
            volumeMounts:
            - mountPath: /etc/medusa/
              name: k8ssandra-prd-medusa-purge-backups-job
            - mountPath: /etc/medusa-secret/
              name: <name-of-azure-blob-storage-secret>
          volumes:
          - name: k8ssandra-prd-medusa-purge-backups-job
            configMap:
              name: k8ssandra-prd-medusa-purge-job-cm
              items:
                - key: medusa.ini
                  path: medusa.ini
          - name: <name-of-azure-blob-storage-secret>
            secret:
              secretName: <name-of-azure-blob-storage-secret>
          tolerations: [] # If you have any
            #- effect: NoSchedule
            #  key: <key>
            #  operator: Equal
            #  value: <value>
          affinity: {} # If you have any
            #nodeAffinity:
            #  requiredDuringSchedulingIgnoredDuringExecution:
            #    nodeSelectorTerms:
            #    - matchExpressions:
            #      - key: <key>
            #        operator: In
            #        values:
            #        - <values>
```

Hopefully this can help someone dealing with this setup.

**Comment by renoypaulose** [comment]
@ajvn, I tried to create the cronjob using the same Docker file. But ended up with the below error when the job was triggered.
```
[2022-05-16 13:56:40,589] ERROR: This error happened during the purge: Azure cli doesn't seem to be installed on this system and is a required dependency for the Azure backend. Please check https://docs.microsoft.com/en-us/cli/azure/install-azure-cli for guidelines.
```
What could be the reason for this?
[purge_error.txt](https://github.com/k8ssandra/k8ssandra/files/8701831/purge_error.txt)

**Comment by ajvn** [comment]
@renoypaulose It looks like it's complaining about lack of Azure CLI, check if image built correctly.
