### ISSUE TITLE
Automated next/stable release versioning strategy

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#557]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
With a versioning and branching strategy defined via #549 we'll next need to implement automation of that release strategy that can produce chart releases to the next and stable chart repositories.

**Comment by adejanovski** [comment]
The upcoming versioning scheme will use a major.minor.patch-SNAPSHOT pattern for the helm charts, allowing us not to upgrade the helm charts version for each commit.

When releasing to the next, it requires to replace the `-SNAPSHOT` with `-<commit sha>` so that we push distinct version numbers and enable us to precisely pinpoint the charts that are being used for each bug report we get from next.

The `next` release workflow needs an additional step to update that number before pushing the Helm charts. This change will not be committed to `main`.

For stable releases, the version number should be set manually (or through automation) and persisted with a commit before tagging the release.

**Comment by jsanda** [comment]
Not to muddy the waters, but I see a problem with using `<commit sha>` for the version number when we push to next. First, let's consider recent commits to main in descending order:

* 5c018349
* 6d7df998
* 09941a57

5c018349 is the most recent commit. According to Semver though 6d7df998 would be last. This would break the semantics of `helm install` installing the latest version by default.

I think the `next` workflow needs to use a monotonically increasing number here.

**Comment by adejanovski** [comment]
what about `<timestamp>-<commit-sha>` then or something like that?

**Comment by jsanda** [comment]
I tend to favor monotonically increasing + sha which would give us,

* 3-5c01834
* 2-6d7df99
* 1-6d7df99

If the user wants to use a version other than the latest, he can easily see the version numbers. We also have the SHA to trace it back to a particular commit. Timestamps would work as well, but they will be harder for users to visually compare IMO.

**Comment by adejanovski** [comment]
It's just that this would require the workflow to compute what's the previous release number before issuing the new one (after incrementing it). Not that it's impossible, just a little more tedious.
How about using the date with format `<yyyyMMddHHmm>-<commit-sha>` ?

Maybe we should dump the sha altogether... It's not that hard to check which action ran at that time and see what was the sha of the commit that triggered it.
