### ISSUE TITLE
Cloud provider performance benchmarking design

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#684]
To be able to prepare performance benchmarking on the various cloud providers we need to first plan a scope and comparison approach.

Hopefully, we can leverage the approach outlined in our [blog](https://k8ssandra.io/blog/2021/03/10/requirements-for-running-k8ssandra-for-development/).

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-466) by [Unito](https://www.unito.io)

**Comment by adejanovski** [comment]
From past experiences I would advise to narrow down our scope pretty strictly, because it'll quickly get crazy complex to perform those benchmarks otherwise:

- A benchmark is only good as a comparison with a reference setup: are we trying to compare cloud providers with each other in the context of K8ssandra or benchmark K8ssandra itself against non k8s Cassandra clusters? 
Trying to compare the cloud providers could come with too many moving parts (what type of instances? Serverless (GKE Autopilot/ EKS Fargate)? what type of storage?).
Comparing a Cassandra cluster deployed on "raw" EC2 instances with an EKS Fargate/GKE Autopilot cluster seems more interesting and easy to achieve. A "classic" EKS/GKE cluster with managed instances could be interesting as well to see if the serverless k8s offerings involve any penalty (if not we can rule them out of the blog post for the sake of simplicity).
- Defining what we're precisely benchmarking is crucial not to get lost with too many settings combinations. Also it helps write a blog post with a story that makes sense.
- We'll have to run some throughput tests and some fixed rate ones
- We need to make sure our stress tests are hitting enough sstables to be representative by monitoring `nodetool tablehistograms` during initial runs. This will tell us if our stress profiles are correctly designed.
- We probably don't want a crazy matrix of versions and should perform all testing against Apache Cassandra 4.0.
- Stargate's impact and elasticity should be evaluated as well (which brings us back to "what are we testing precisely?"). This could very well be fit for a second blog post as it could already be off topic.

My go to would be to test a single cloud provider serverless managed k8s service against an instance based cluster that would serve as reference, using 4.0 and G1GC with a 31G heap. It'll bring us closer to the benchmarks that were performed in [this blog post](https://thelastpickle.com/blog/2020/06/29/cassandra_4-0_garbage_collectors_performance_benchmarks.html).

The story behind the first blog post could be: is Cassandra's performance comparable when moving to a k8s based cluster running in the cloud?
The second one: how much elasticity does Stargate bring to Cassandra and what's its impact on performance and TCO?
