### ISSUE TITLE
Upgrade k8ssandra to latest k8ssandra/cass-operator release when available

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#693]

**Comment by jsanda** [comment]
This will be cass-operator 1.7.0. 

Since we have CRD changes in cass-operator we will need #137 as well. k8ssandra itself does not need the CRD changes. We could just upgrade cass-operator in k8ssandra without also upgrading the CRD, and I think things would work. My strong preference though would be to keep the operation version and CRD used by k8ssandra in sync. 

@burmanm thoughts?
